### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by mato** [mirage/mirage-entropy#38]
We are missing `aarch64` support in `lib/native/entropy_cpu_stubs.c`. I have opened https://github.com/ocaml/opam-repository/pull/12228 to disable installing on unsupported archs for now.

@Weichen81 AFAIK you had a patch for this?

**Comment by yomimono** [comment]
Just had someone run into this on IRC - would this be a huge amount of work to implement?

**Comment by reynir** [comment]
I was the one complaining on IRC o/

I found some assembly from a mini-os fork with aarch64 code and copied it. It compiles and runs. I don't fully understand the code, but I can make a pull request. https://github.com/reynir/mirage-entropy/commits/aarch64

**Comment by hannesm** [comment]
@reynir would be nice to get a PR with your changes!  then we'll need someone to understand + review the change :)

**Comment by Weichen81** [comment]
@mato Sorry for replying later. Yes, I have modified the mirage-entropy to run conduit_server on AArch64. But it's not easy for me to release this patch soon (Same as most companies, we need time to pass internal progress ). But I think I can comment on @reynir 's PR

**Comment by hannesm** [comment]
merged #39
