### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [mirage/mirage-entropy#42]
Currently the latest release in opam is 0.2.0, which depends on camlp4: http://opam.ocaml.org/packages/mirage-entropy-unix/

It makes sense to make a new one, since the dependency was removed. Also maybe to include https://github.com/mirage/mirage-entropy/pull/41.

**Comment by hannesm** [comment]
Dear @XVilka, thanks for your question.

The mirage-entropy-unix/mirage-entropy-xen packages are part of the mirage 2.x series, which is no longer the current one.

These packages have been superseeded by the `mirage-entropy` package, which latest release is 0.4.1 (not depending on camlp4).

#41 is a draft PR that depends on various other moving bits and pieces, and as far as I can see not yet ready to be merged and released.
